package app

var CommonPorts = map[int]PortInfo{
	0:  {Port: 20, Type: "tcp", Service: "ftp-data"},
	1:  {Port: 21, Type: "tcp", Service: "ftp"},
	2:  {Port: 22, Type: "tcp", Service: "ssh"},
	3:  {Port: 23, Type: "tcp", Service: "telnet"},
	4:  {Port: 25, Type: "tcp", Service: "smtp"},
	5:  {Port: 53, Type: "tcp", Service: "domain"},
	6:  {Port: 67, Type: "udp", Service: "dhcp-server"},
	7:  {Port: 68, Type: "udp", Service: "dhcp-client"},
	8:  {Port: 69, Type: "udp", Service: "tftp"},
	9:  {Port: 80, Type: "tcp", Service: "http"},
	10: {Port: 110, Type: "tcp", Service: "pop3"},
	11: {Port: 111, Type: "tcp", Service: "rpcbind"},
	12: {Port: 123, Type: "udp", Service: "ntp"},
	13: {Port: 135, Type: "tcp", Service: "msrpc"},
	14: {Port: 137, Type: "udp", Service: "netbios-ns"},
	15: {Port: 138, Type: "udp", Service: "netbios-dgm"},
	16: {Port: 139, Type: "tcp", Service: "netbios-ssn"},
	17: {Port: 143, Type: "tcp", Service: "imap"},
	18: {Port: 161, Type: "udp", Service: "snmp"},
	19: {Port: 389, Type: "tcp", Service: "ldap"},
	20: {Port: 443, Type: "tcp", Service: "https"},
	21: {Port: 445, Type: "tcp", Service: "microsoft-ds"},
	22: {Port: 465, Type: "tcp", Service: "smtps"},
	23: {Port: 587, Type: "tcp", Service: "submission"},
	24: {Port: 636, Type: "tcp", Service: "ldaps"},
	25: {Port: 993, Type: "tcp", Service: "imaps"},
	26: {Port: 995, Type: "tcp", Service: "pop3s"},
	27: {Port: 1025, Type: "tcp", Service: "NFS-or-IIS"},
	28: {Port: 1080, Type: "tcp", Service: "socks"},
	29: {Port: 1433, Type: "tcp", Service: "ms-sql-s"},
	30: {Port: 1521, Type: "tcp", Service: "oracle"},
	31: {Port: 1723, Type: "tcp", Service: "pptp"},
	32: {Port: 2049, Type: "tcp", Service: "nfs"},
	33: {Port: 3306, Type: "tcp", Service: "mysql"},
	34: {Port: 3389, Type: "tcp", Service: "ms-wbt-server"},
	35: {Port: 5432, Type: "tcp", Service: "postgresql"},
	36: {Port: 5900, Type: "tcp", Service: "vnc"},
	37: {Port: 6001, Type: "tcp", Service: "X11:1"},
	38: {Port: 6379, Type: "tcp", Service: "redis"},
	39: {Port: 8080, Type: "tcp", Service: "http-proxy"},
	40: {Port: 8443, Type: "tcp", Service: "https-alt"},
	41: {Port: 9001, Type: "tcp", Service: "tor-orport"},
}
